name: keyboard_shortcuts
description: Widget that allow you to use shortcuts for your application. Custom shortcuts that you define by yourself and global like auto scroll to bottom and top.
version: 0.1.4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.2.2
  tuple: ^2.0.1
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter